export interface PricingModel{
  applicationName:string;
  phoneNumber: string;
  address: string;
  loanDate: string;
  loanOfficer:string ;
  branchOffice:string ;
  branchaddress:string ;
  calcDate: string;
  fsaguarantee: number;
  loantype: number;
  lienpos: number;
  loanAmnt: number;
  paymentfreq: number;
  pd: number;
  ballonyrs:number;
  locateral: number;
  feeAmnt: number;
  lgd: number;
  ballon: number;
  AmorType1: string;
  AmorTerm1: number;
  loanProd1: number;
  TransferOption1:string;
  IntRate1: number;
  PayAmnt1: number;
  AmorType2: string;
  AmorTerm2: number;
  loanProd2: number;
  TransferOption2: string;
  IntRate2: number;
  PayAmnt2: number;
  AmorType3: string
  AmorTerm3: number;
  loanProd3: number;
  TransferOption3: string;
  IntRate3: number;
  PayAmnt3: number;
  RecomRate1: number;
  RecomSpread1: number;
  Variance1: number;
  finalSpread1: number;
  RecomRate2: number;
  RecomSpread2: number;
  Variance2:number;
  finalSpread2: number;
  RecomRate3: number;
  RecomSpread3: number;
  Variance3: number;
  finalSpread3: number;
}